# https://docs.codecov.com/docs/codecov-yaml
# https://docs.codecov.com/docs/commit-status
# https://docs.codecov.com/docs/codecov-yaml#validate-your-repository-yaml
# Validate with:
# curl --data-binary @.github/codecov.yml https://codecov.io/validate
coverage:
  status:
    project:
      default:
        target: 0% # TODO: test: revert to "auto" once the project has more coverage
        threshold: 60% # TODO: test: review once the project has more coverage
        base: auto
        paths:
          - "src"
    patch:
      default:
        target: 0% # TODO: test: revert to "auto" once the project has more coverage
        threshold: 60% # TODO: test: review once the project has more coverage
        base: auto
        paths:
          - "src"
